/**
 * Galician translation
 * https://github.com/Rubarez/elFinder-Language
 * @author Rubén Álvarez Mel <rubencalvinmel@gmail@gmail.com>
 * @version 2014-05-14
 */
if (elFinder && elFinder.prototype && typeof(elFinder.prototype.i18) == 'object') {
	elFinder.prototype.i18.gl = {
		translator : 'Rubén Álvarez Mel &lt;rubencalvinmel@gmail.com&gt;',
		language   : 'Galego (Galician)',
		direction  : 'ltr',
		messages   : {
			
			/********************************** errors **********************************/
			'error'                : 'Erro',
			'errUnknown'           : 'Erro descoñecido.',
			'errUnknownCmd'        : 'Comando descoñecido.',
			'errJqui'              : 'Configuración non válida de jQuery UI. Deben estar incluidos os compoñentes selectable, draggable e droppable.',
			'errNode'              : 'elFinder necesita crear elementos DOM.',
			'errURL'               : 'Configuración non válida de elFinder! A opción URL non está configurada.',
			'errAccess'            : 'Acceso denegado.',
			'errConnect'           : 'No se puido conectar co backend.',
			'errAbort'             : 'Conexión cancelada.',
			'errTimeout'           : 'Conexión cancelada por tempo de espera.',
			'errNotFound'          : 'Backend no encontrado.',
			'errResponse'          : 'Resposta non válida do backend.',
			'errConf'              : 'Configuración non válida do backend .',
			'errJSON'              : 'O módulo PHP JSON non está instalado.',
			'errNoVolumes'         : 'Non hai volumes dispoñibles que sexan lexibles.',
			'errCmdParams'         : 'Parámetros non válidos para o comando "$1".',
			'errDataNotJSON'       : 'Os datos non están en formato JSON.',
			'errDataEmpty'         : 'Non hai datos.',
			'errCmdReq'            : 'A petición do backend necesita un nome de comando.',
			'errOpen'              : 'Non se pode abrir "$1".',
			'errNotFolder'         : 'O obxeto non é una carpeta.',
			'errNotFile'           : 'O obxeto non é un arquivo.',
			'errRead'              : 'Non se pode ler "$1".',
			'errWrite'             : 'Non se pode escribir en "$1".',
			'errPerm'              : 'Permiso denegado.',
			'errLocked'            : '"$1" está bloqueado e nob pode ser renomeado, movido ou borrado.',
			'errExists'            : 'Xa existe un arquivo chamado "$1".',
			'errInvName'           : 'Nome de arquivo non válido.',
			'errFolderNotFound'    : 'Carpeta non atopada.',
			'errFileNotFound'      : 'Arquivo no atopada.',
			'errTrgFolderNotFound' : 'Carpeta de destino "$1" no atopada.',
			'errPopup'             : 'O navegador impide abrir as novas ventanas. Pode activalo nas opcións do navegador.',
			'errMkdir'             : 'Non se pode crear a carpeta "$1".',
			'errMkfile'            : 'Non se pode crear o arquivo "$1".',
			'errRename'            : 'Non se pode renomear "$1".',
			'errCopyFrom'          : 'Non se permite copiar arquivos desde el volume "$1".',
			'errCopyTo'            : 'Non se permite copiar arquivos ó volume "$1".',
			'errUploadCommon'      : 'Erro no envío.',
			'errUpload'            : 'Non se pode subir "$1".',
			'errUploadNoFiles'     : 'Non hai arquivos para subir.',
			'errMaxSize'           : 'O tamaño dos datos excede o máximo permitido.',
			'errFileMaxSize'       : 'O tamaño do arquivo excede o máximo permitido.',
			'errUploadMime'        : 'Tipo de arquivo non permitidp.',
			'errUploadTransfer'    : 'Erro o transferir "$1".', 
			'errSave'              : 'Non se pode gardar "$1".',
			'errCopy'              : 'Non se pode copiar "$1".',
			'errMove'              : 'Non se pode mover "$1".',
			'errCopyInItself'      : 'Non se pode copiar "$1" into itself.',
			'errRm'                : 'Non se pode borrar "$1".',
			'errExtract'           : 'Non se pode extraer arquivos desde "$1".',
			'errArchive'           : 'Non se pode crear el arquivo.',
			'errArcType'           : 'Tipo de arquivo non soportado.',
			'errNoArchive'         : 'O arquivo non é de tipo arquivo ou é de un tipo non soportado.',
			'errCmdNoSupport'      : 'O backend non soporta este comando.',
			'errReplByChild'       : 'A carpeta “$1” non puede ser reemplazada por un elemento contido nela.',
			'errArcSymlinks'       : 'Por razóns de seguridade non se pode descomprimir arquivos que conteñan symlinks.',
			'errArcMaxSize'        : 'O tamaño do arquivo excede o máximo permitido.',
			
			/******************************* commands names ********************************/
			'cmdarchive'   : 'Crear arquivo',
			'cmdback'      : 'Atrás',
			'cmdcopy'      : 'Copiar',
			'cmdcut'       : 'Cortar',
			'cmddownload'  : 'Descargar',
			'cmdduplicate' : 'Duplicar',
			'cmdedit'      : 'Editar arquivo',
			'cmdextract'   : 'Extraer elementos do arquivo',
			'cmdforward'   : 'Adiante',
			'cmdgetfile'   : 'Seleccionar arquivos',
			'cmdhelp'      : 'Acerca deste software',
			'cmdhome'      : 'Inicio',
			'cmdinfo'      : 'Obter información',
			'cmdmkdir'     : 'Nova carpeta',
			'cmdmkfile'    : 'Novo arquivos de texto',
			'cmdopen'      : 'Abrir',
			'cmdpaste'     : 'Pegar',
			'cmdquicklook' : 'Previsualizar',
			'cmdreload'    : 'Recargar',
			'cmdrename'    : 'Cambiar nome',
			'cmdrm'        : 'Eliminar',
			'cmdsearch'    : 'Buscar arquivos',
			'cmdup'        : 'Ir á carpeta raíz',
			'cmdupload'    : 'Subir arquivos',
			'cmdview'      : 'Ver',
			
			/*********************************** buttons ***********************************/ 
			'btnClose'  : 'Pechar',
			'btnSave'   : 'Gardar',
			'btnRm'     : 'Eliminar',
			'btnCancel' : 'Cancelar',
			'btnNo'     : 'Non',
			'btnYes'    : 'Sí',
			
			/******************************** notifications ********************************/
			'ntfopen'     : 'Abrir carpeta',
			'ntffile'     : 'Abrir arquivos',
			'ntfreload'   : 'Actualizar contido da carpeta',
			'ntfmkdir'    : 'Creando directorio',
			'ntfmkfile'   : 'Creando arquivos',
			'ntfrm'       : 'Eliminndo arquivos',
			'ntfcopy'     : 'Copiar arquivos',
			'ntfmove'     : 'Mover arquivos',
			'ntfprepare'  : 'Preparar copia de arquivos',
			'ntfrename'   : 'Renomear arquivos',
			'ntfupload'   : 'Subindo arquivos',
			'ntfdownload' : 'Descargando arquivos',
			'ntfsave'     : 'Gardar arquivos',
			'ntfarchive'  : 'Creando arquivos',
			'ntfextract'  : 'Extraendo elementos do arquivo',
			'ntfsearch'   : 'Buscando arquivos',
			'ntfsmth'     : 'Facendo algo >_<',
      'ntfloadimg'  : 'Cargando imaxe',
			
			/************************************ dates **********************************/
			'dateUnknown' : 'descoñecida',
			'Today'       : 'Hoxe',
			'Yesterday'   : 'Onte',
			'Jan'         : 'Xan',
			'Feb'         : 'Feb',
			'Mar'         : 'Mar',
			'Apr'         : 'Abr',
			'May'         : 'Mai',
			'Jun'         : 'Xuñ',
			'Jul'         : 'Xul',
			'Aug'         : 'Ago',
			'Sep'         : 'Sep',
			'Oct'         : 'Out',
			'Nov'         : 'Nov',
			'Dec'         : 'Dec',

			/********************************** messages **********************************/
			'confirmReq'      : 'Necesítase confirmación',
			'confirmRm'       : '¿Está seguro de querer eliminar arquivos?<br/>Esto non ten volta atrás!',
			'confirmRepl'     : '¿Reemplazar o antigo arquivo co novo?',
			'apllyAll'        : 'Aplicar a todo',
			'name'            : 'Nome',
			'size'            : 'Tamaño',
			'perms'           : 'Permisos',
			'modify'          : 'Modificado',
			'kind'            : 'Tipo',
			'read'            : 'lectura',
			'write'           : 'escritura',
			'noaccess'        : 'sen acceso',
			'and'             : 'e',
			'unknown'         : 'descoñecido',
			'selectall'       : 'Seleccionar tódolos arquivos',
			'selectfiles'     : 'Seleccionar arquivo(s)',
			'selectffile'     : 'Seleccionar primer arquivo',
			'selectlfile'     : 'Seleccionar último arquivo',
			'viewlist'        : 'ver como lista',
			'viewicons'       : 'Ver como iconos',
			'places'          : 'Lugares',
			'calc'            : 'Calcular', 
			'path'            : 'Ruta',
			'aliasfor'        : 'Alias para',
			'locked'          : 'Bloqueado',
			'dim'             : 'Dimensións',
			'files'           : 'Arquivos',
			'folders'         : 'Carpetas',
			'items'           : 'Elementos',
			'yes'             : 'si',
			'no'              : 'non',
			'link'            : 'Enlace',
			'searcresult'     : 'Resultados da búsqueda',  
			'selected'        : 'elementos seleccionados',
			'about'           : 'Acerca',
			'shortcuts'       : 'Accesos directos',
			'help'            : 'Axuda',
			'webfm'           : 'Administrador de arquivos web',
			'ver'             : 'Version',
			'protocol'        : 'versión do protocolo',
			'homepage'        : 'Project home',
			'docs'            : 'Documentación',
			'github'          : 'Fork us on Github',
			'twitter'         : 'Síguenos en Twitter',
			'facebook'        : 'Únete a nos en Facebook',
			'team'            : 'Equipo',
			'chiefdev'        : 'desarrollador xefe',
			'developer'       : 'desarrollador',
			'contributor'     : 'contribuinte',
			'maintainer'      : 'mantedor',
			'translator'      : 'traductor',
			'icons'           : 'Iconos',
			'dontforget'      : 'e non olvide traer a súa toalla',
			'shortcutsof'     : 'Accesos directos desactivados',
			'dropFiles'       : 'Arrastre arquivos aquí',
			'or'              : 'o',
			'selectForUpload' : 'Seleccione arquivos para subir',
			'moveFiles'       : 'Mover arquivos',
			'copyFiles'       : 'Copiar arquivos',
			'rmFromPlaces'    : 'Eliminar nas súas ubicacións',
			'untitled folder' : 'carpeta sin título',
			'untitled arquivo.txt' : 'Arquivo.txt sen título',
      'mode'            : 'Modo',
      'resize'          : 'Redimensionar',
      'crop'            : 'Recortar',
			
			/********************************** mimetypes **********************************/
			'kindUnknown'     : 'Descoñecido',
			'kindFolder'      : 'Carpeta',
			'kindAlias'       : 'Alias',
			'kindAliasBroken' : 'Alias roto',
			// applications
			'kindApp'         : 'Aplicación',
			'kindPostscript'  : 'Documento Postscript',
			'kindMsOffice'    : 'Documento Microsoft Office',
			'kindMsWord'      : 'Documento Microsoft Word',
			'kindMsExcel'     : 'Documento Microsoft Excel',
			'kindMsPP'        : 'Presentación Microsoft Powerpoint',
			'kindOO'          : 'Documento Open Office',
			'kindAppFlash'    : 'Aplicación Flash',
			'kindPDF'         : 'Documento PDF',
			'kindTorrent'     : 'Arquivo Bittorrent',
			'kind7z'          : 'Arquivo 7z',
			'kindTAR'         : 'Arquivo TAR',
			'kindGZIP'        : 'Arquivo GZIP',
			'kindBZIP'        : 'Arquivo BZIP',
			'kindZIP'         : 'Arquivo ZIP',
			'kindRAR'         : 'Arquivo RAR',
			'kindJAR'         : 'Arquivo Java JAR',
			'kindTTF'         : 'Fonte True Type',
			'kindOTF'         : 'Fonte Open Type',
			'kindRPM'         : 'Paquete RPM',
			// texts
			'kindText'        : 'Documento de texto',
			'kindTextPlain'   : 'Texto plano',
			'kindPHP'         : 'Código PHP',
			'kindCSS'         : 'Folla de estilo CSS',
			'kindHTML'        : 'Documento HTML',
			'kindJS'          : 'Código Javascript',
			'kindRTF'         : 'Documento RTF',
			'kindC'           : 'C source',
			'kindCHeader'     : 'Código C header',
			'kindCPP'         : 'Código C++',
			'kindCPPHeader'   : 'Código C++ header',
			'kindShell'       : 'Script Unix shell',
			'kindPython'      : 'Código Python',
			'kindJava'        : 'Código Java',
			'kindRuby'        : 'Código Ruby',
			'kindPerl'        : 'Código Perl',
			'kindSQL'         : 'SCódigo QL',
			'kindXML'         : 'Documento XML',
			'kindAWK'         : 'Código AWK source',
			'kindCSV'         : 'Documento CSV (valores separados por comas)',
			'kindDOCBOOK'     : 'Documento Docbook XML',
			// images
			'kindImage'       : 'Imaxe',
			'kindBMP'         : 'Imaxe BMP',
			'kindJPEG'        : 'Imaxe JPEG',
			'kindGIF'         : 'Imaxe GIF',
			'kindPNG'         : 'Imaxe PNG',
			'kindTIFF'        : 'Imaxe TIFF',
			'kindTGA'         : 'Imaxe TGA',
			'kindPSD'         : 'Imaxe Adobe Photoshop',
			'kindXBITMAP'     : 'Imaxe X bitmap',
			'kindPXM'         : 'Imaxe Pixelmator',
			// media
			'kindAudio'       : 'Audio media',
			'kindAudioMPEG'   : 'Audio MPEG',
			'kindAudioMPEG4'  : 'Audio MPEG-4',
			'kindAudioMIDI'   : 'Audio MIDI',
			'kindAudioOGG'    : 'Audio Ogg Vorbis',
			'kindAudioWAV'    : 'Audio WAV',
			'AudioPlaylist'   : 'Lista de reproducción MP3',
			'kindVideo'       : 'Video media',
			'kindVideoDV'     : 'Película DV',
			'kindVideoMPEG'   : 'Película MPEG',
			'kindVideoMPEG4'  : 'Película MPEG-4',
			'kindVideoAVI'    : 'Película AVI',
			'kindVideoMOV'    : 'Película Quick Time',
			'kindVideoWM'     : 'Película Windows Media',
			'kindVideoFlash'  : 'Película Flash',
			'kindVideoMKV'    : 'Película Matroska MKV',
			'kindVideoOGG'    : 'Película Ogg'
		}
	}
}

